{lib, ...}: let
  digits = map toString (lib.range 0 9);
  mouseButtons = ["leftmouse" "middlemouse" "rightmouse" "mouseback" "mouseforward" "mouse1" "mouse2"];
  commandKeys =
    lib.stringToCharacters "abcdefgijklnopqrstuvwxyz"
    ++ digits
    ++ ["comma" "semicolon" "slash" "backslash" "leftbrace" "rightbrace" "equal" "minus" "enter"];
  # Physical Ctrl+Option+Cmd must behave like the Caps Lock Hyper layer,
  # including when Shift is held. Otherwise Cmd's application translations
  # swallow the Super modifier and make Hyper depend on key press order.
  hyperKeys =
    lib.stringToCharacters "abcdefghijklmnopqrstuvwxyz"
    ++ digits
    ++ mouseButtons
    ++ ["comma" "semicolon" "slash" "backslash" "leftbrace" "rightbrace" "equal" "minus" "enter" "esc" "space" "tab" "grave" "dot" "left" "right" "up" "down" "home" "end" "pageup" "pagedown" "backspace" "delete"];
  withModifiers = modifiers: keys: lib.genAttrs keys (key: "${modifiers}-${key}");
in {
  services.keyd = {
    enable = true;
    keyboards.default = {
      # The wildcard only matches keyboards. Keep the relative mouse devices
      # in this same config so clicks can see the keyboard's Cmd/Ctrl layers.
      # Do not wildcard pointers: keyd does not preserve touchpad gestures.
      # keyd 2.6 forwards conventional wheel ticks, not high-resolution scroll.
      ids = [
        "*"
        "m:3434:d031" # Keychron Link
        "m:19f5:3255" # NuPhy Air60 V2 mouse interface
      ];
      settings = {
        global.overload_tap_timeout = 250;
        main = {
          capslock = "overload(hyper, tab)";
          # The existing Alt/Meta swap makes the physical Command key emit Meta.
          # Untranslated Cmd chords retain Super for the desktop shortcuts.
          leftalt = "layer(cmd)";
          leftmeta = "layer(alt)";
          rightalt = "layer(cmd)";
          rightmeta = "layer(alt)";
          "leftshift+rightshift" = "capslock";
        };
        shift = {
          esc = "S-`";
        };
        alt = {
          # Option+Left/Right moves by word; Shift extends the selection.
          # Leave Alt+Up/Down to applications (for example, moving lines).
          left = "C-left";
          right = "C-right";
          backspace = "C-backspace";
          delete = "C-delete";
        };
        control = {
          # macOS Control-click is a secondary click, not tab/link selection.
          leftmouse = "rightmouse";
          # Give physical Ctrl+number its own compositor shortcut. Cmd+number
          # emits Ctrl+number directly, without re-entering this layer, so it
          # reaches application tabs. Holding Shift still moves windows.
          "1" = "C-M-1";
          "2" = "C-M-2";
          "3" = "C-M-3";
          "4" = "C-M-4";
          "5" = "C-M-5";
          "6" = "C-M-6";
          "7" = "C-M-7";
          "8" = "C-M-8";
          "9" = "C-M-9";
          # Keep physical Control navigation separate from the Ctrl events
          # generated by Option's word movement above.
          left = "C-M-left";
          right = "C-M-right";
          up = "C-M-up";
        };
        "cmd:M" =
          withModifiers "C" (commandKeys ++ mouseButtons)
          // {
            # Cmd+H/M are reserved: Niri has no native hide/minimize action.
            # Cmd+Q uses the application's normal quit shortcut, not a kill.
            # Mouse bindings are real button events, so clicks can be held.
            left = "home";
            right = "end";
            up = "C-home";
            down = "C-end";
            backspace = "macro(S-home backspace)";
            delete = "macro(S-end delete)";
            dot = "esc";
          };
        "hyper:C-M-A" = {};
      };
      # Composite layers must follow their custom constituent layer. Putting
      # these in settings would sort cmd+shift before cmd:M and break keyd.
      extraConfig = lib.generators.toINI {} {
        "cmd+shift" = {
          leftbrace = "C-pageup";
          rightbrace = "C-pagedown";
          "3" = "M-S-3";
          "4" = "M-S-4";
          "5" = "M-S-5";
          q = "M-S-q";
        };
        "cmd+alt" = {
          left = "C-pageup";
          right = "C-pagedown";
          d = "M-A-d";
          esc = "M-A-esc";
        };
        "cmd+control" =
          withModifiers "C-M" digits
          // withModifiers "C" mouseButtons
          // {
            leftmouse = "C-rightmouse";
            f = "M-C-f";
            q = "M-C-q";
            space = "M-C-space";
          };
        "cmd+alt+shift" = {
          # Paste and match style. Explicitly consume all three modifiers.
          v = "C-S-v";
          # Keep the confirmation even with Option held during logout.
          q = "M-S-q";
        };
        "cmd+control+shift" = {
          # F3/F4 avoid Ctrl+Shift+3/4's workspace movement output.
          "3" = "M-S-f3";
          "4" = "M-S-f4";
        };
        "cmd+alt+control" = withModifiers "C-M-A" hyperKeys;
        "cmd+alt+control+shift" = withModifiers "C-M-A-S" hyperKeys;
        "hyper+shift" = withModifiers "C-M-A-S" hyperKeys;
      };
    };
  };

  # keyd 2.6 drops to the keyd group at startup. The upstream NixOS unit only
  # keeps CAP_SYS_NICE, so setgid fails unless CAP_SETGID is added explicitly.
  systemd.services.keyd.serviceConfig.CapabilityBoundingSet = lib.mkAfter ["CAP_SETGID"];

  users.groups.keyd = {};
}
