{
  pkgs,
  inputs,
  ...
}: let
  customPkgs = import ../../pkgs {inherit pkgs;};
in {
  environment.systemPackages = with pkgs;
    [
      astro-language-server
      bash-language-server
      biome
      bluetui
      brightnessctl
      bun
      cargo
      cargo-binstall
      cifs-utils
      claude-agent-acp
      claude-code
      clippy
      cmake
      codex-acp
      colima
      comma
      cosign
      curl
      customPkgs.dcd
      deno
      eog
      fastfetch
      fd
      fuse
      gh
      gnome-themes-extra
      go
      go-tools
      google-chrome
      gopls
      gotools
      gradle
      gum
      herdr
      hunk
      hyperfine
      customPkgs.icloud-linux
      jq
      just
      kcl
      kdePackages.breeze
      kdePackages.breeze-icons
      kdePackages.dolphin
      kdePackages.kcalc
      kdePackages.kio
      kdePackages.kio-extras
      kdePackages.kio-fuse
      kdePackages.qtsvg
      kiro-cli
      kotlin
      labwc
      lima
      lisette
      lua-language-server
      maven
      meson
      mpv
      nautilus
      neovim
      ninja
      nodejs
      obsidian
      opam
      pkl
      playerctl
      pnpm
      customPkgs.prism
      protobuf
      pyright
      ripgrep
      ruff
      rust-analyzer
      rustc
      rustfmt
      samba
      sd
      sfwbar
      stylua
      svelte-language-server
      swiftformat
      tailwindcss-language-server
      tokei
      tree-sitter
      typst
      unzip
      usage
      usbutils
      uv
      vscode-langservers-extracted
      vtsls
      vue-language-server
      wiremix
      wl-clipboard
      xwayland-satellite
      yaml-language-server
      yazi
      yt-dlp
      zed-editor
      zig
      zip
    ]
    ++ [inputs.opencode-v2.packages.${pkgs.stdenv.hostPlatform.system}.default];
}
